### PR TITLE
Add currentRoute helper

### PR DESCRIPTION
**Pull request by sungwoncho**
I find this useful when adding a CSS class dynamically based on the current template's name. Doing so allows me to nest CSS rules under the scope of individual templates.

i.e.

```
<div class={{currentRoute}}>
  ...
</div>
```

[FlowRouter. getRouteName()](https://github.com/kadirahq/flow-router#flowroutergetroutename) is a reactive data source, and so this helper is also reactive.

Will be happy to update the doc if this is mergeable.

### CODE REVIEW

**Comment by zimme** [comment]
Maybe it should be `{{currentRouteName}}` or `{{routeName}}` to make it clear that it's the current route's name and not it's path?

**Comment by banglashi** [comment]
Hi @sungwoncho,
since arillo:flow-router-helpers has a dependency to zimme:active-route isn't your use case fulfilled with this helper? 

``` handlebars
<li class="{{isActiveRoute class='is-selected' name='home'}}">...</li>
```

You can pass the class it should return with the class parameter. You also have isActivePath available.

**Comment by zimme** [comment]
@banglashi, his use case differs from what my helpers are intended for. Sure he could technically use my helpers to get the result he wants, but if would be unnecessarily complex because he only need the current routes name and not check if it matches something.

**Comment by banglashi** [comment]
@zimme I see, I misunderstood the use case then. I would go with `{{currentRouteName}}` then. @sungwoncho if it is ok for you I can add it to the package.

**Comment by zimme** [comment]
@sungwoncho, This is actually a nice use case which I haven't thought about myself. I think I'll add it to my arsenal of Meteor "weapons" :+1:

**Comment by banglashi** [comment]
ok, done. https://atmospherejs.com/arillo/flow-router-helpers

**Pull request closed without merging**
